### ISSUE TITLE
您好，请问像这种自己修改网络结构后的预训练权重是怎么得到的呢？

### ISSUE THREAD

**Issue by Fafa-DL** [bubbliiiing/mobilenet-yolov4-keras#2]
比如随便写了个网络A，这个网络肯定没有预训练权重，那是不是需要在voc上进行训练得到权重？请问作者一般是怎么设置训练参数，比如周期，学习率等，谢谢！

**Comment by bubbliiiing** [comment]
主干权重有就行，所以建议用已有的主干，在后面该网络

**Comment by Fafa-DL** [comment]
> 主干权重有就行，所以建议用已有的主干，在后面该网络

那请问主干和融合网络全改了，是不是要从0训练了？一般先在哪个数据集训练呢？训练多少个epoch？谢谢作者，一直在关注您

**Comment by bubbliiiing** [comment]
问题汇总

**Comment by 351470549** [comment]
> 主干权重有就行，所以建议用已有的主干，在后面该网络

请问ghostnet的keras权重文件可以分享一下吗

**Comment by bubbliiiing** [comment]
emm，我转换的并不全面

**Comment by bubbliiiing** [comment]
很需要吗，可以直接用我训练好的这个么
